steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - asia.gcr.io/kancollewidget/ocr-api
    - '.'
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - asia.gcr.io/kancollewidget/ocr-api
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ocr-api
    - --image
    - asia.gcr.io/kancollewidget/ocr-api
    - --region
    - asia-northeast1
    - --platform
    - managed
images:
- asia.gcr.io/kancollewidget/ocr-api